#!/bin/sh
# \
exec wish "$0" ${1+"$@"}

# Let's find system directory
if {![info exists env(NNACSSYSDIR)]} {
    # Not defined special place -> let's use the default one
    set dir [file join $env(HOME) noclab]
} else {
    set dir $env(NNACSSYSDIR)
}

set sysdir [file join $dir scripts]
puts "Script directory: $sysdir" 
pkg_mkIndex $sysdir
lappend auto_path $sysdir
source [file join $sysdir main.tcl]

# End of file
